[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/r/*"
  to = "/.netlify/functions/r?pid=:splat"
  status = 302
  force = true


[[redirects]]
  from = "/en/qr.html"
  to = "/en/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/de/qr.html"
  to = "/de/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/ar/qr.html"
  to = "/ar/index.html"
  status = 301
  force = true
# deploy bump
